[package]
name = "fprint-prompt"
version = "0.1.0"
edition = "2021"

[dependencies]
dbus = "0.9.7"
env_logger             = "0.11.5"
heck = "0.5.0"
log                    = "0.4.22"
smithay-client-toolkit = "0.19.2"
wayland-client         = "0.31.5"
